- function: malloc
  model:
    - return_effect: alloc
      arguments:
        - none

- function: aligned_alloc
  model:
    - return_effect: alloc
      arguments:
        - none
        - none

- function: zmalloc
  model:
    - return_effect: alloc
      arguments:
        - none

- function: xmalloc
  model:
    - return_effect: alloc
      arguments:
        - none

- function: safe_malloc
  model:
    - return_effect: alloc
      arguments:
        - none

- function: safemalloc
  model:
    - return_effect: alloc
      arguments:
        - none

- function: calloc
  model:
    - return_effect: alloc
      arguments:
        - none
        - none

- function: xcalloc
  model:
    - return_effect: alloc
      arguments:
        - none
        - none

- function: safe_calloc
  model:
    - return_effect: alloc
      arguments:
        - none
        - none

- function: safecalloc
  model:
    - return_effect: alloc
      arguments:
        - none
        - none

- function: realloc
  model:
    - return_effect: realloc_res
      arguments:
        - realloc_ptr
        - none

- function: lalloc
  model:
    - return_effect: alloc
      arguments:
        - none
        - none

- function: lalloc_clear
  model:
    - return_effect: alloc
      arguments:
        - none
        - none

- function: nhalloc
  model:
    - return_effect: alloc
      arguments:
        - none
        - none

- function: oballoc
  model:
    - return_effect: alloc
      arguments:
        - none
        - none

- function: printf
  model:
    - return_effect: none
      arguments:
        - none

- function: memcpy
  model:
    - return_effect: none
      arguments:
        - assign_trg
        - deref_src
        - none
    - return_effect: copy_trg
      arguments:
        - src
        - none
        - none

- function: memset
  model:
    - return_effect: none
      arguments:
        - assign_trg
        - src
        - none
    - return_effect: copy_trg
      arguments:
        - src
        - none
        - none

- function: asprintf
  model:
    - return_effect: none
      arguments:
        - alloc
        - none
        - none

- function: bindtextdomain
  model:
    - return_effect: static_alloc
      arguments:
        - none
        - none

- function: bind_textdomain_codeset
  model:
    - return_effect: static_alloc
      arguments:
        - none
        - none

- function: canonicalize_file_name
  model:
    - return_effect: alloc
      arguments:
        - none

- function: cap_get_file
  model:
    - return_effect: alloc
      arguments:
        - none

- function: cap_to_text
  model:
    - return_effect: alloc
      arguments:
        - none

- function: __ctype_b_loc
  model:
    - return_effect: static_alloc
      arguments:

- function: dcgettext
  model:
    - return_effect: static_alloc
      arguments:
        - none
        - none
        - none

- function: dlerror
  model:
    - return_effect: alloc
      arguments:

- function: dlopen
  model:
    - return_effect: alloc
      arguments:
        - none
        - none

- function: dlsym
  model:
    - return_effect: unknown
      arguments:
        - none
        - none

- function: __errno_location
  model:
    - return_effect: static_alloc
      arguments:

- function: fdopen
  model:
    - return_effect: alloc
      arguments:
        - none
        - none

- function: fdopendir
  model:
    - return_effect: alloc
      arguments:
        - none

- function: fopen
  model:
    - return_effect: alloc
      arguments:
        - none
        - none

- function: freopen
  model:
    - return_effect: copy_trg
      arguments:
        - none
        - none
        - src

- function: gai_strerror
  model:
    - return_effect: alloc
      arguments:
        - none

- function: getaddrinfo
  model:
    - return_effect: alloc
      arguments:

- function: getcwd
  model:
    - return_effect: realloc_res
      arguments:
        - realloc_ptr
        - none

- function: getdelim
  model:
    - return_effect: none
      arguments:
        - alloc
        - none

- function: getline
  model:
    - return_effect: none
      arguments:
        - alloc

- function: getenv
  model:
    - return_effect: static_alloc
      arguments:
        - none

- function: getgrent
  model:
    - return_effect: static_alloc
      arguments:

- function: getgrgid
  model:
    - return_effect: static_alloc
      arguments:
        - none

- function: getgrnam
  model:
    - return_effect: static_alloc
      arguments:
        - none

- function: getlogin
  model:
    - return_effect: static_alloc
      arguments:

- function: getpwnam
  model:
    - return_effect: static_alloc
      arguments:
        - none

- function: getpwuid
  model:
    - return_effect: static_alloc
      arguments:
        - none
- function: getpwuid
  model:
    - return_effect: static_alloc
      arguments:
        - none

- function: gettext
  model:
    - return_effect: static_alloc
      arguments:
        - none

- function: getutxent
  model:
    - return_effect: static_alloc
      arguments:

- function: gmtime_r
  model:
    - return_effect: copy_trg
      arguments:
        - none
        - src

- function: iconv
  model:
    - return_effect: none
      arguments:
        - none
        - deref_src
        - none
        - assign_trg
        - none

- function: iconv_open
  model:
    - return_effect: alloc
      arguments:
        - none
        - none

- function: localeconv
  model:
    - return_effect: static_alloc
      arguments:

- function: localtime_r
  model:
    - return_effect: copy_trg
      arguments:
        - none
        - src

- function: localtime
  model:
    - return_effect: static_alloc
      arguments:
        - none

- function: ngettext
  model:
    - return_effect: alloc
      arguments:
        - none
        - none
        - none

- function: nl_langinfo
  model:
      - return_effect: alloc
        arguments:
          - none

- function: opendir
  model:
      - return_effect: alloc
        arguments:

- function: memchr
  model:
      - return_effect: copy_trg
        arguments:
          - src
          - none
          - none

- function: memrchr
  model:
      - return_effect: copy_trg
        arguments:
          - src
          - none
          - none

- function: newlocale
  model:
      - return_effect: alloc
        arguments:

- function: rawmemchr
  model:
      - return_effect: copy_trg
        arguments:
          - src
          - none

- function: readdir
  model:
      - return_effect: alloc
        arguments:
          - none

- function: re_compile_pattern
  model:
      - return_effect: alloc
        arguments:
          - none

- function: __sched_cpualloc
  model:
      - return_effect: static_alloc
        arguments:

- function: secure_getenv
  model:
    - return_effect: static_alloc
      arguments:
        - none

- function: setlocale
  model:
      - return_effect: static_alloc
        arguments:
          - none
          - none

- function: signal
  model:
    - return_effect: alloc
      arguments:
        - none
        - none

- function: stpcpy
  model:
    - return_effect: none
      arguments:
        - assign_trg
        - deref_src
    - return_effect: copy_trg
      arguments:
        - src
        - none

- function: strcat
  model:
    - return_effect: none
      arguments:
        - assign_trg
        - deref_src
    - return_effect: copy_trg
      arguments:
        - src
        - none

- function: strcpy
  model:
    - return_effect: none
      arguments:
        - assign_trg
        - deref_src
    - return_effect: copy_trg
      arguments:
        - src
        - none

- function: strchr
  model:
    - return_effect: copy_trg
      arguments:
        - src
        - none

- function: strdup
  model:
    - return_effect: alloc
      arguments:
        - none

- function: strerror
  model:
    - return_effect: alloc
      arguments:
        - none

- function: strerror_r
  model:
    - return_effect: copy_trg
      arguments:
        - none
        - src
        - none

- function: strncat
  model:
    - return_effect: none
      arguments:
        - assign_trg
        - deref_src
        - none
    - return_effect: copy_trg
      arguments:
        - src
        - none
        - none

- function: strncpy
  model:
    - return_effect: none
      arguments:
        - assign_trg
        - deref_src
        - none
    - return_effect: copy_trg
      arguments:
        - src
        - none
        - none

- function: strpbrk
  model:
    - return_effect: copy_trg
      arguments:
        - src
        - none

- function: strrchr
  model:
    - return_effect: copy_trg
      arguments:
        - src
        - none

- function: strsignal
  model:
    - return_effect: alloc
      arguments:
        - none

- function: strstr
  model:
    - return_effect: copy_trg
      arguments:
        - src

- function: strtod
  model:
    - return_effect: none
      arguments:
        - src
        - assign_trg

- function: strtod_l
  model:
    - return_effect: none
      arguments:
        - src
        - assign_trg
        - none

- function: strtof
  model:
    - return_effect: none
      arguments:
        - src
        - assign_trg

- function: strtof_l
  model:
    - return_effect: none
      arguments:
        - src
        - assign_trg
        - none

- function: strtok
  model:
    - return_effect: copy_trg
      arguments:
        - src

- function: strtol
  model:
    - return_effect: none
      arguments:
        - src
        - assign_trg
        - none

- function: strtold
  model:
    - return_effect: none
      arguments:
        - src
        - assign_trg

- function: strtold_l
  model:
    - return_effect: none
      arguments:
        - src
        - assign_trg

- function: __isoc23_strtol
  model:
    - return_effect: none
      arguments:
        - src
        - assign_trg
        - none

- function: strtoul
  model:
    - return_effect: none
      arguments:
        - src
        - assign_trg
        - none

- function: __isoc23_strtoul
  model:
    - return_effect: none
      arguments:
        - src
        - assign_trg
        - none

- function: strtoumax
  model:
    - return_effect: none
      arguments:
        - src
        - assign_trg
        - none

- function: __isoc23_strtoumax
  model:
    - return_effect: none
      arguments:
        - src
        - assign_trg
        - none

- function: strtoimax
  model:
    - return_effect: none
      arguments:
        - src
        - assign_trg
        - none

- function: __isoc23_strtoimax
  model:
    - return_effect: none
      arguments:
        - src
        - assign_trg
        - none

- function: textdomain
  model:
    - return_effect: alloc
      arguments:
        - none

- function: ttyname
  model:
    - return_effect: alloc
      arguments:
        - none

- function: vasprintf
  model:
    - return_effect: none
      arguments:
        - alloc
        - none
        - none
