- function: malloc
  model:
    return_effect: alloc
    arguments:
      - none

- function: printf
  model:
    return_effect: none
    arguments:
      - none

- function: memcpy
  model:
    return_effect: none
    arguments:
      - assign_trg
      - deref_src
      - none

- function: realloc
  model:
    return_effect: realloc_res
    arguments:
      - realloc_ptr
      - none
